package com.websystique.springmvc.model;

//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2016.04.28 at 11:08:53 AM BST 
//

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/*
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Hotel", propOrder = {
 "hotelid",
 "name",
 "address1",
 "address2",
 "postalCode",
 "thumbNail",
 "rate"
})*/


@XmlRootElement(name = "hotelsummary")
public class HotelSummary implements Serializable {
	@XmlElement
	public int getHotelid() {
		return hotelid;
	}

	public void setHotelid(int hotelid) {
		this.hotelid = hotelid;
	}


 protected int hotelid;

 protected String name;

 protected String address1;

 protected String address2;

 protected String postalcode;

 protected String thumbnailurl;

 protected String lowrate;
 

 protected String locationdescription;

 public String getPostalcode() {
	return postalcode;
}

public void setPostalcode(String postalcode) {
	this.postalcode = postalcode;
}
@XmlElement
public String getThumbnailurl() {	
	if (thumbnailurl!=null && !thumbnailurl.isEmpty()) thumbnailurl = thumbnailurl.replace("_t.", "_l.");
	return thumbnailurl;
}

public void setThumbnailurl(String thumbnailurl) {
	this.thumbnailurl = thumbnailurl;
}
@XmlElement
public String getLowrate() {
	return lowrate;
}

public void setLowrate(String lowrate) {
	this.lowrate = lowrate;
}
@XmlElement
public String getLocationdescription() {
	return locationdescription;
}

public void setLocationdescription(String locationdescription) {
	this.locationdescription = locationdescription;
}
@XmlElement
public String getCountrycode() {
	return countrycode;
}

public void setCountrycode(String countrycode) {
	this.countrycode = countrycode;
}
@XmlElement
public String getRatecurrencycode() {
	return ratecurrencycode;
}

public void setRatecurrencycode(String ratecurrencycode) {
	this.ratecurrencycode = ratecurrencycode;
}


 protected String countrycode;
 

 protected String ratecurrencycode;
 
 
  


 protected String shortdescription;
 


 


 @XmlElement
 public String getShortdescription() {
	return shortdescription;
}

public void setShortdescription(String shortdescription) {
	this.shortdescription = shortdescription;
}


protected String city;
 
	@XmlElement
 public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}
 

 /**
  * Gets the value of the name property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
	@XmlElement
 public String getName() {
     return name;
 }

 /**
  * Sets the value of the name property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setName(String value) {
     this.name = value;
 }

 /**
  * Gets the value of the address1 property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 @XmlElement
 public String getAddress1() {
     return address1;
 }

 /**
  * Sets the value of the address1 property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setAddress1(String value) {
     this.address1 = value;
 }

 /**
  * Gets the value of the address2 property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 @XmlElement
 public String getAddress2() {
     return address2;
 }

 /**
  * Sets the value of the address2 property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setAddress2(String value) {
     this.address2 = value;
 }



 

 @Override
 public String toString() {
     return "Hotel:"
       +hotelid
      +"|"+name
      +"|"+address1 
      +"|"+address2 
      +"|"+postalcode 
      +"|"+thumbnailurl 
      +"|"+lowrate;
     
 }    
 
 public HotelSummary(){}
}
